[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/onam"
  to = "https://mon.school/code-a-pookkalam"
  status = 200
  force = true